dist: xenial
language: python
sudo: false
cache: pip

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
    - pip install tox tox-travis codecov

script: tox

after_success:
    - codecov

notifications:
  email: false
