# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsm_log', '0003_statelog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statelog',
            name='object_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
